name: deployment
on:
  push:
    branches: [main]
jobs:
  install:
    runs-on: bee
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Environment
        run: |
          npm i -g yarn
          echo "${{ secrets.ENV }}" > .env
          echo "NODE_ENV='production'" >> .env
          echo "${{ secrets.RSA }}" > rsa.cert
          chmod 400 ./rsa.cert
      - name: Build
        run: |
          chmod +x ./scripts/vps/build-ci.sh;
          source ./scripts/vps/build-ci.sh;
      - name: Upload
        run: |
          chmod +x ./scripts/vps/upload-ci.sh
          source ./scripts/vps/upload-ci.sh "s3.ocopee.com" "ocopee_ui"
